### ISSUE TITLE
Build source Dong Du

### ISSUE THREAD

**Issue by binhvq** [rockkhuya/DongDu#2]
Chào anh Tuấn Anh!
Em cố gắng build lại phần mềm nhưng không được
Em dùng ubuntu.
Khi build báo thiếu file learner.h và predictor.h
em mới nghiên cứu về xử lý ngôn ngữ nên có nhiều chỗ không hiểu ạ!
Cảm ơn anh!

**Comment by iamloivx** [comment]
Cập nhật để anh chị em nào chưa sử dụng được DongDu.

Sử dụng bản binary từ http://viet.jnlp.org/dongdu tại [https://dl.dropboxusercontent.com/u/2152477/SNOW-Vietnamese/bin.zip](https://dl.dropboxusercontent.com/u/2152477/SNOW-Vietnamese/bin.zip)


Khi chạy DongDu trên Centos 7 x64, cần cài đặt thêm `glibc.i686` và `libstdc++.so.6`.

```
yum install -y glibc.i686
yum install -y libstdc++.so.6
```
